config/routes.rb
Rails.application.routes.draw do

  resources :lists
  resources :cards

  resources :boards

  root to: "home#index"

  get 'home' => 'home#index'

  get 'index' => 'home#index'

end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :lists
  has_many :cards
end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :board, counter_cache: true
  belongs_to :list, counter_cache: true
end

app/models/label.rb
class Label < ActiveRecord::Base
  belongs_to :board
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :board
  has_many :cards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render action: 'show', status: :created, location: @board }
      else
        format.html { render action: 'new' }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:name, :trello_id, :cards_count, :trello_url, :last_sync_date)
    end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render action: 'show', status: :created, location: @card }
      else
        format.html { render action: 'new' }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:title, :trello_id, :url, :board_id, :points)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    render :index
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render action: 'show', status: :created, location: @list }
      else
        format.html { render action: 'new' }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:trello_id, :name, :closed, :position)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/application/_page_title.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><%= title %></h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

app/views/boards/_form.html.erb
<%= form_for(@board) do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :trello_id %>
    <%= f.text_field :trello_id,:class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :trello_url %>
    <%= f.text_field :trello_url,:class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :last_sync_date %>
    <%= f.datetime_select :last_sync_date, :class => "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-default" %>
  </div>
<% end %>
</form>

app/views/boards/edit.html.erb
<div id="page-wrapper">
  <%= render 'page_title', title: "Editing Board" %>
  <%= render 'form' %>

  <%= link_to 'Show', @board %> |
  <%= link_to 'Back', boards_path %>
</div>

app/views/boards/index.html.erb
<div id="page-wrapper">
  <%= render 'page_title', title: "Trello Boards" %>
  <div class="row">
    <div class="col-md-12">
      <div class="table-responsive">
         <table class="table table-striped table-bordered table-hover">
           <thead>
             <tr>
               <th>Name</th>
               <th>Trello Id</th>
               <th>URL</th>
               <th>Cards Count</th>
               <th>Last sync date</th>
               <th></th>
               <th></th>
               <th></th>
             </tr>
           </thead>
           <tbody>
             <% @boards.each do |board| %>
               <tr>
                 <td><%= board.name %></td>
                 <td><%= board.trello_id %></td>
                 <td><%= board.trello_url %></td>
                 <td><%= board.cards_count %></td>
                 <td><%= board.last_sync_date %></td>
                 <td><%= link_to 'Show', board %></td>
                 <td><%= link_to 'Edit', edit_board_path(board) %></td>
                 <td><%= link_to 'Destroy', board, method: :delete, data: { confirm: 'Are you sure?' } %></td>
               </tr>
             <% end %>
           </tbody>
        </table>
      </div>
    </div>
  </div>
  <br>
  <%= link_to 'New Board', new_board_path %>
</div>

app/views/boards/new.html.erb
<div id="page-wrapper">
  <h1>New board</h1>

  <%= render 'form' %>
  <%= link_to 'Back', boards_path %>
</div>

app/views/boards/show.html.erb
<div id="page-wrapper">
  <%= render 'page_title', title: "Show Board" %>

  <p id="notice"><%= notice %></p>

  <form class="form">
    <div class="form-group">
      <label class="col-sm-2 control-label">Name</label>
      <div class="col-sm-10">
        <p class="form-control-static"><%= @board.name %></p>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Trello Id</label>
      <div class="col-sm-10">
        <p class="form-control-static"><%= @board.trello_id %></p>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Trello URL</label>
      <div class="col-sm-10">
        <p class="form-control-static"><%= @board.trello_url %></p>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Cards Count</label>
      <div class="col-sm-10">
        <p class="form-control-static"><%= @board.cards_count %></p>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Last Sync Date</label>
      <div class="col-sm-10">
        <p class="form-control-static"><%= @board.last_sync_date %></p>
      </div>
    </div>
  </form>

  <%= link_to 'Edit', edit_board_path(@board) %> |
  <%= link_to 'Back', boards_path %>
</div>

app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :trello_id %><br>
    <%= f.text_field :trello_id, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :short_id %><br>
    <%= f.text_field :short_id, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :trello_url %><br>
    <%= f.text_field :trello_url, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :board_id %><br>
    <%= f.number_field :board_id, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :points %><br>
    <%= f.text_field :points, :class => "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<div id="page-wrapper">
  <%= render 'page_title', title: "Editing Card" %>
  <%= render 'form' %>

  <%= link_to 'Show', @card %> |
  <%= link_to 'Back', cards_path %>
</div>

app/views/cards/index.html.erb
<div id="page-wrapper">
  <%= render 'page_title', title: "Trello Cards" %>
  <div class="row">
    <div class="col-md-12>"
      <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
          <thead>
            <tr>
              <th>Card No.</th>
              <th>Title</th>
              <th>Trello</th>
              <th>Board</th>
              <th>Points</th>
              <th></th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @cards.each do |card| %>
              <tr>
                <td><a href="<%= card.trello_url %>" target="_blank"><%= card.short_id %></a></td>
                <td><%= card.name %></td>
                <td><%= card.trello_id %></td>
                <td><%= card.board_id %></td>
                <td><%= card.points %></td>
                <td><%= link_to 'Show', card %></td>
                <td><%= link_to 'Edit', edit_card_path(card) %></td>
                <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <br>
  <%= link_to 'New Card', new_card_path %>
</div>

app/views/cards/new.html.erb
<div id="page-wrapper">
  <%= render 'page_title', title: "New Card" %>
  <%= render 'form' %>

  <%= link_to 'Back', cards_path %>
</div>

app/views/cards/show.html.erb
<div id="page-wrapper">
  <%= render 'page_title', title: "Show Card" %>
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= @card.name %>
  </p>

  <p>
    <strong>Trello:</strong>
    <%= @card.trello_id %>
  </p>

  <p>
    <strong>Card No:</strong>
    <a href="<%= @card.trello_url %>" target="_blank"><%= @card.short_id %></a>
  </p>

  <p>
    <strong>Board:</strong>
    <%= @card.board_id %>
  </p>

  <p>
    <strong>Points:</strong>
    <%= @card.points %>
  </p>

  <%= link_to 'Edit', edit_card_path(@card) %> |
  <%= link_to 'Back', cards_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ScrummyTrello</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'navigation' %>

<%= yield %>

<%= javascript_include_tag "application", "data-turbolinks-track" => true %>

</body>
</html>

app/views/lists/_form.html.haml
= form_for @list do |f|
  - if @list.errors.any?
    #error_explanation
      %h2= "#{pluralize(@list.errors.count, "error")} prohibited this list from being saved:"
      %ul
        - @list.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :trello_id
    = f.text_field :trello_id
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :closed
    = f.text_field :closed
  .field
    = f.label :position
    = f.text_field :position
  .actions
    = f.submit 'Save'

app/views/lists/edit.html.haml
%h1 Editing list

= render 'form'

= link_to 'Show', @list
\|
= link_to 'Back', lists_path

app/views/lists/index.html.haml
#page-wrapper
  = render 'page_title', :title => 'Trello Boards'
  .row
    .col-md-12
      .table-responsive
        %table.table.table-striped.table-bordered.table-hover
          %thead
            %tr
              %th Trello
              %th Name
              %th Closed
              %th Position
              %th
              %th
              %th

          %tbody
          - @lists.each do |list|
            %tr
              %td= list.trello_id
              %td= list.name
              %td= list.closed
              %td= list.position
              %td= link_to 'Show', list
              %td= link_to 'Edit', edit_list_path(list)
              %td= link_to 'Destroy', list, :method => :delete, :data => { :confirm => 'Are you sure?' }

  %br
  .row
    = link_to 'New List', new_list_path

app/views/lists/new.html.haml
%h1 New list

= render 'form'

= link_to 'Back', lists_path

app/views/lists/show.html.haml
%p#notice= notice

%p
  %b Trello:
  = @list.trello_id
%p
  %b Name:
  = @list.name
%p
  %b Closed:
  = @list.closed
%p
  %b Position:
  = @list.position

= link_to 'Edit', edit_list_path(@list)
\|
= link_to 'Back', lists_path